theme: minima
title: Their Computer
author: MojoExMachina
email: response@their.computer
description: > # this means to ignore newlines until "baseurl:"
  It's their computer, after all.
  
# social links
github_username:  MojoExMachina # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
